### ISSUE TITLE
Use readers instead of pulling everything into memory

### ISSUE THREAD

**Issue by jcbwlkr** [smotes/purse#1]
This project looks pretty neat. I like the idea of keeping things simple. One thing you might consider is making the `fixtures` map a `map[string]io.Reader` instead of `map[string]string`. You can probably cut down on some of the code inside `purse.New` and you avoid reading all of the files into memory until they're asked for in `Get`. 

This blog post explains the idea very well http://jmoiron.net/blog/crossing-streams-a-love-letter-to-ioreader/

**Comment by smotes** [comment]
This is definitely a good suggestion as it could drastically lower the memory footprint. However I'm a little skeptical about managing the file descriptors. If a given file's contents are read in as bytes (string) each time the `Get` method is evoked, there needs to exist a way to eventually call `Close` on all the file descriptors loaded into the map. So the `fixtures` map would actually need to look something like `map[string]io.ReaderCloser` to give it a more flexible interface. Can you foresee any major issues with having a map of open file descriptors throughout a program's execution? Obviously you'd run into file permission issues if trying to write to one of the opened files, but that arguably shouldn't be happening anyways while a program is actively running. Thoughts?

**Comment by jcbwlkr** [comment]
Hmm... yeah I don't know. I am really not very experienced with this so I can't say for sure. I know in general you can run in to OS level problems of "too many open files" but I'm not sure if you'd realistically hit that.

Another alternative would be to make it a map of `map[string]os.FileInfo` (http://golang.org/pkg/os/#FileInfo) and read the file contents out on demand? Or have an intermediate struct that holds the `os.FileInfo` and the contents from the first time you try to read it.

Don't listen to me though, I don't know what I'm talking about (^_^) My gut feeling from articles like the one I posted is that `io.Reader` is usually what you'd want to use but I don't have enough to back that up.

**Comment by elithrar** [comment]
I think before you went down the "on demand" path it might be worth
benchmarking the "time to first read + buffer" to measure what the
performance impact is. Even for large, multi-line queries you're still only
storing a few hundred/thousand bytes per query. It'd take a lot of these
queries to add up to any measurable memory impact.

io.Reader is good practice to be sure, especially when you're streaming
things in from disk and don't know the size and/or don't trust the size
(both are reasonable things to do!).

In this case, I think slurping it all in at once it okay (given our
concerns for latency) and/or using io.Reader to slurp it all during
start-up. You might use io.Reader *if* you want to parse the contents first
(i.e. ignoring or parsing SQL comments to allow multiple queries per file)
rather than copying strings everywhere.

**Comment by smotes** [comment]
I did some benchmarking on the `Get` method and tested both approaches, with and without the `io.ReaderCloser` interface and `ioutil.ReadAll` on each call. On my machine this was showing benchmark numbers of ~4000 ns/op compared to ~30 ns/op when loading the file contents once and keeping it all in memory, which is unsurprisingly two orders of magnitude faster when comparing them relatively. I'm going to keep it as is for now.

> I think before you went down the "on demand" path it might be worth
benchmarking the "time to first read + buffer" to measure what the
performance impact is. Even for large, multi-line queries you're still only
storing a few hundred/thousand bytes per query. It'd take a lot of these
queries to add up to any measurable memory impact.

> io.Reader is good practice to be sure, especially when you're streaming
things in from disk and don't know the size and/or don't trust the size
(both are reasonable things to do!).

> In this case, I think slurping it all in at once it okay (given our
concerns for latency) and/or using io.Reader to slurp it all during
start-up. You might use io.Reader *if* you want to parse the contents first
(i.e. ignoring or parsing SQL comments to allow multiple queries per file)
rather than copying strings everywhere.

**Comment by jcbwlkr** [comment]
@smotes: sounds reasonable enough. As @elithrar wisely pointed out benchmarking is definitely the way to go. Thanks for the conversation and considering different approaches (^_^)
